language: node_js
node_js:
  - 4.5.0
services:
  - mongod
env:
  global:
    - NODE_ENV: tst
addons:
  sauce_connect: true
notifications:
  - raul.pereira@gmail.com
before_install:
  - npm install -g bower@1.7.9
  - npm install -g grunt-cli@1.2.0
  - npm install -g karma-cli@1.0.1
  - npm install -g protractor@4.0.5
  - webdriver-manager update
  - bower install
before_script:
  - node test/data.js
  - grunt
  - cd dist
script:
  - karma start config/karma.config.js --single-run --browsers PhantomJS
  - node server &
  - protractor config/protractor.config.js